SELECT
	a.TABLE_TYPE				as 表格類型,
	a.TABLE_NAME				as 表格名稱,
	b.COLUMN_NAME				as 欄位名稱,
	(
		SELECT
			value
		FROM
			fn_listextendedproperty (NULL, 'schema', 'dbo', 'table',
				a.TABLE_NAME, 'column', default)
		WHERE
			name='MS_Description' 
			and objtype='COLUMN' 
			and objname Collate Chinese_Taiwan_Stroke_CI_AS = b.COLUMN_NAME
	)					as 欄位備註,	
	b.DATA_TYPE				as 資料型別,
	b.CHARACTER_MAXIMUM_LENGTH		as 最大長度,
	b.IS_NULLABLE				as 允許空值,
	b.NUMERIC_PRECISION			as 數字長度,
	b.NUMERIC_SCALE				as 小數位數,
	b.COLUMN_DEFAULT			as 預設值,
	b.ORDINAL_POSITION 			as 欄位順序,
	c.ParentTable				as 主鍵資料表
FROM
	INFORMATION_SCHEMA.TABLES  a
	LEFT JOIN INFORMATION_SCHEMA.COLUMNS b ON ( a.TABLE_NAME=b.TABLE_NAME )
	LEFT JOIN 
	(
		SELECT	INFORMATION_SCHEMA.TABLE_CONSTRAINTS.TABLE_NAME AS ChildTable, 
					CONSTRAINT_COLUMN_USAGE_1.COLUMN_NAME AS ChildColID, 
					INFORMATION_SCHEMA.REFERENTIAL_CONSTRAINTS.CONSTRAINT_NAME AS ConstraintName,
					INFORMATION_SCHEMA.CONSTRAINT_TABLE_USAGE.TABLE_NAME AS ParentTable,
					INFORMATION_SCHEMA.CONSTRAINT_COLUMN_USAGE.COLUMN_NAME AS ParentColID
		FROM	INFORMATION_SCHEMA.CONSTRAINT_COLUMN_USAGE INNER JOIN
					INFORMATION_SCHEMA.CONSTRAINT_TABLE_USAGE INNER JOIN
					INFORMATION_SCHEMA.TABLE_CONSTRAINTS INNER JOIN
					INFORMATION_SCHEMA.REFERENTIAL_CONSTRAINTS ON 
					INFORMATION_SCHEMA.TABLE_CONSTRAINTS.CONSTRAINT_NAME = INFORMATION_SCHEMA.REFERENTIAL_CONSTRAINTS.CONSTRAINT_NAME ON 
					INFORMATION_SCHEMA.CONSTRAINT_TABLE_USAGE.CONSTRAINT_NAME = INFORMATION_SCHEMA.REFERENTIAL_CONSTRAINTS.UNIQUE_CONSTRAINT_NAME ON 
					INFORMATION_SCHEMA.CONSTRAINT_COLUMN_USAGE.CONSTRAINT_NAME =
					INFORMATION_SCHEMA.CONSTRAINT_TABLE_USAGE.CONSTRAINT_NAME AND
					INFORMATION_SCHEMA.CONSTRAINT_COLUMN_USAGE.TABLE_NAME = INFORMATION_SCHEMA.CONSTRAINT_TABLE_USAGE.TABLE_NAME INNER JOIN
					INFORMATION_SCHEMA.CONSTRAINT_COLUMN_USAGE AS CONSTRAINT_COLUMN_USAGE_1 ON 
					INFORMATION_SCHEMA.TABLE_CONSTRAINTS.CONSTRAINT_NAME = CONSTRAINT_COLUMN_USAGE_1.CONSTRAINT_NAME AND 
					INFORMATION_SCHEMA.TABLE_CONSTRAINTS.TABLE_NAME = CONSTRAINT_COLUMN_USAGE_1.TABLE_NAME
	) as c ON c.ChildTable = a.TABLE_NAME and  c.ChildColID = b.COLUMN_NAME
Where a.TABLE_TYPE = 'BASE TABLE' And a.TABLE_NAME not like 'aspnet_%'
ORDER BY a.TABLE_NAME, ordinal_position